In [24]:
import numpy as np
from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F

In [21]:
x = torch.empty(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
x = torch.tensor([5.5, 3])
print(x)
x = x.new_ones(2, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)
print(x.size())
y = torch.rand(2, 3)
print(x + y)
print(torch.add(x, y))
result = torch.empty(2, 3)
print('')
print(result)
torch.add(x, y, out=result)
print(result)
print(x[:, 1])

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.4602, 0.0000]])
tensor([[0.2914, 0.2938, 0.0202],
        [0.3950, 0.0320, 0.2296],
        [0.6824, 0.5426, 0.8713],
        [0.4143, 0.7721, 0.8926],
        [0.7755, 0.6123, 0.5219]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8532, -0.4986, -0.1433],
        [-0.0861,  0.0510,  0.6298]])
torch.Size([2, 3])
tensor([[-0.7724,  0.1579, -0.0824],
        [ 0.7262,  0.7587,  1.4280]])
tensor([[-0.7724,  0.1579, -0.0824],
        [ 0.7262,  0.7587,  1.4280]])

tensor([[-13370010.0000,         0.0000,         0.0000],
        [        0.0000,         0.0000,         0.0000]])
tensor([[-0.7724,  0.1579, -0.0824],
        [ 0.7262,  0.7587,  1.4280]])
tensor([-0.4986,  0.0510])


In [22]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [56]:
img = torch.tensor([[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10], [6, 3, 7, 1]],
                    [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10], [6, 3, 7, 1]]], dtype=torch.float)
# img = torch.randn(1, 1, 4, 4)
print(img)
img = img.view(1, 2, 4, 4)
print(img)
print('------------')
c = nn.Conv2d(2, 3, 2)
params = list(c.parameters())
print(params[0].size())
print(params)
print(c)
res = c(img)
print('Result')
print(res.size())
print(res)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.],
         [ 7.,  8.,  9., 10.],
         [ 6.,  3.,  7.,  1.]],

        [[ 1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.],
         [ 7.,  8.,  9., 10.],
         [ 6.,  3.,  7.,  1.]]])
tensor([[[[ 1.,  2.,  3.,  4.],
          [ 4.,  5.,  6.,  7.],
          [ 7.,  8.,  9., 10.],
          [ 6.,  3.,  7.,  1.]],

         [[ 1.,  2.,  3.,  4.],
          [ 4.,  5.,  6.,  7.],
          [ 7.,  8.,  9., 10.],
          [ 6.,  3.,  7.,  1.]]]])
------------
torch.Size([3, 2, 2, 2])
[Parameter containing:
tensor([[[[ 0.2613,  0.2349],
          [ 0.1702, -0.1244]],

         [[-0.0902,  0.0163],
          [-0.1869,  0.3002]]],


        [[[-0.3406,  0.1360],
          [ 0.2382,  0.1007]],

         [[ 0.3008,  0.2864],
          [-0.0576,  0.3363]]],


        [[[ 0.1201,  0.2932],
          [ 0.0023, -0.1204]],

         [[-0.2740,  0.0210],
          [ 0.2490,  0.1346]]]], requires_grad=True), Parameter containing:
tensor

In [58]:
0.2613*1 + 0.2349*2 + 0.1702*4 - 0.1244*5 - 0.0902*1 + 0.0163*2 + -0.1869*4 + 0.3002*5 + 0.1655

1.6512

In [59]:
0.2613*2 + 0.2349*3 + 0.1702*5 - 0.1244*6 - 0.0902*2 + 0.0163*3 + -0.1869*5 + 0.3002*6 + 0.1655

2.2326